# Generated by Django 5.0.7 on 2024-08-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
